name: msgo-infra
services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: msgo_user
      POSTGRES_PASSWORD: msgo_password
      POSTGRES_DB: msgo_db
    ports:
      - 5432:5432

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - 4222:4222
      - 8222:8222
