openapi: 3.0.0
info:
  title: User Service
  description: API for user management and authentication
  version: 1.0.0
servers:
  - url: http://localhost:4001
tags:
  - name: Health

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
        required:
          - error
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          description: Status of the service
          enum: [ok]
paths:
  /health:
    get:
      tags:
        - Health
      summary: Health check
      description: Returns the health of the service
      operationId: healthCheck
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
